## Relación y unión de bases de datos
Análisis de datos y *Big Data*</br>
Eduación Continua | Universidad de los Andes.</br>
**Módulo 1**

Frecuentemente vamos a tener información en tablas separadas que vamos a tener que unir para poder:
* Relacionar columnas que están en tablas distintas
* Considerar todas filas a la vez, que quedaron en tablas distintas

Existen al menos 3 librerías en Python para hacer estas uniones. Pero nosotros vamos a usar:
- append para pegar filas (ahora concat)
- join para pegar columnas

Tarea: consultar y probar **merge**

In [2]:
import pandas as pd

### Append: pegarle más filas

DataFrame.**append**(other, ignore_index=False, verify_integrity=False, sort=False)

Parámetros:
<ul>
    <li><b>other</b>: Información para unir. Permite DF, Series, Diccionarios o listas.</li>
    <li><b>ignore_index</b>: Booleano. Si es verdadero el índice queda numerado de 0 a n.</li>
    <li><b>verify_integrity</b>: Booleano. Si es verdadero crea un error al crear un índice duplicado.</li>
    <li><b>sort</b>: Booleano. Deja organizar el DF.</li>
</ul>

El método **append** será deprecado de la librería por lo tanto se recomienda utilizar **concat** en su lugar.

In [3]:
# Creamos unas tablas de prueba
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'), index=['x', 'y'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'), index=['x', 'y'])
l1 = ["a", "b"]

In [3]:
df

   A  B
x  1  2
y  3  4

In [4]:
df2

   A  B
x  5  6
y  7  8

In [4]:
df_combined = pd.concat([df, df2], ignore_index=True)
df_combined

   A  B
0  1  2
1  3  4
2  5  6
3  7  8

**Ejercicio:** Cuales son los parámetros de la función concat?

In [8]:
# Intentemos cambiando el valor en ignore_index y veamos que pasa
df = pd.concat([df, df2], ignore_index=True)
df

   A  B
0  1  2
1  3  4
2  5  6
3  7  8

In [5]:
# Que pasa si tenemos una lista
df = pd.concat([df, l1], ignore_index=True)

TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid

In [10]:
#Podemos convertir la lista en un dataframe y usar concat
l1_df = pd.DataFrame([l1], columns=df.columns)
df = pd.concat([df, l1_df], ignore_index=True)
df

   A  B
0  1  2
1  3  4
2  5  6
3  7  8
4  a  b

**Podemos sólo agregarla en la última posición, si la lista corresponde con las columnas**

In [11]:
df.loc[len(df)]=l1
df

   A  B
0  1  2
1  3  4
2  5  6
3  7  8
4  a  b
5  a  b

### Join: pegarle más columnas

DataFrame.**join**(other, on=None, how='left', lsuffix='', rsuffix='', sort=False, validate=None)

Parámetros:
<ul>
    <li><b>other</b>: Objetos para unir. Permite DF o Series.</li>
    <li><b>on</b>: str. Llave por la cual se van a unir las bases.</li>
    <li><b>how</b>: str. Método para unir los objetos.</li>
    <li><b>lsufix</b>: str. Complementos a los nombres de las variables para diferenciar entre los objetos (Izquierda).</li>
    <li><b>rsufix</b>: str. Complementos a los nombres de las variables para diferenciar entre los objetos (Derecha).</li>
    <li><b>sort</b>: Bool. Ordenar por el índice.</li>
    <li><b>validate</b>: str. Verifica si el cruce se realizó 1:1, 1:m o m:1.</li>
</ul>

In [12]:
dfa = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5'],
                   'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']})
dfb = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']})

In [13]:
dfa

  key   A
0  K0  A0
1  K1  A1
2  K2  A2
3  K3  A3
4  K4  A4
5  K5  A5

In [14]:
dfb

  key   B
0  K0  B0
1  K1  B1
2  K2  B2

In [15]:
dfa.join(dfb, lsuffix='_A', rsuffix='_B')

  key_A   A key_B    B
0    K0  A0    K0   B0
1    K1  A1    K1   B1
2    K2  A2    K2   B2
3    K3  A3   NaN  NaN
4    K4  A4   NaN  NaN
5    K5  A5   NaN  NaN

In [16]:
dfa.join(dfb.set_index('key'), on='key')

  key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2   B2
3  K3  A3  NaN
4  K4  A4  NaN
5  K5  A5  NaN

También hay configuraciones con las que podemos jugar para quedarnos con las filas que están en una tabla y no en la otra; o bien en ambas, etc. Con esas podemos jugar, o podemos meramente eliminar lo que no queremos después de hacer la unión.

**Ejercicio:** Pegar la columna C del siguiente dataframe, a la base dfb a partir de la columna key.

¿Qué función deberíamos usar? append o join

In [17]:
dfc = pd.DataFrame({'key': ['K0', 'K2'],
                      'C': ['C0', 'C2']})
dfc

  key   C
0  K0  C0
1  K2  C2

In [ ]:
# RESPUESTA:

**Tipos de Join**

El parámetro how determina cómo se realizará la unión entre dos DataFrames. Aquí hay algunos de los valores más comunes para el parámetro how:

* **left:** Devuelve todas las filas del DataFrame de la izquierda y las filas coincidentes del DataFrame de la derecha. Las filas del DataFrame resultante tendrán NaN en las columnas que no se hayan encontrado en el DataFrame de la derecha.
* **right:** Devuelve todas las filas del DataFrame de la derecha y las filas coincidentes del DataFrame de la izquierda. Las filas del DataFrame resultante tendrán NaN en las columnas que no se hayan encontrado en el DataFrame de la izquierda.
* **inner:** Devuelve solo las filas que tienen una clave coincidente en ambos DataFrames.
* **outer:** Devuelve todas las filas de ambos DataFrames, con NaN donde no haya coincidencias.

### **Ejercicios**

Dados los siguientes conjuntos de datos utilice el método conveniente de modo que se unan los dos dataframes.

In [2]:
import pandas as pd

In [3]:
# Crear DataFrames de empleados y departamentos
empleados = pd.DataFrame({'ID_empleado': [1, 2, 3, 4],
                          'Nombre': ['Alice', 'Bob', 'Charlie', 'David'],
                          'ID_departamento': [101, 102, 101, 103]})

departamentos = pd.DataFrame({'ID_departamento': [101, 102, 103],
                              'Nombre_departamento': ['Ventas', 'Marketing', 'TI']})

In [4]:
empleados

   ID_empleado   Nombre  ID_departamento
0            1    Alice              101
1            2      Bob              102
2            3  Charlie              101
3            4    David              103

In [5]:
departamentos

   ID_departamento Nombre_departamento
0              101              Ventas
1              102           Marketing
2              103                  TI

In [6]:
df_union = empleados.join(departamentos.set_index('ID_departamento'), on='ID_departamento')
df_union

   ID_empleado   Nombre  ID_departamento Nombre_departamento
0            1    Alice              101              Ventas
1            2      Bob              102           Marketing
2            3  Charlie              101              Ventas
3            4    David              103                  TI

In [7]:
empleados.join(departamentos.set_index('ID_departamento'), on='ID_departamento', how='right')

   ID_empleado   Nombre  ID_departamento Nombre_departamento
0            1    Alice              101              Ventas
2            3  Charlie              101              Ventas
1            2      Bob              102           Marketing
3            4    David              103                  TI

Una los dataframes "datos" y "nuevos_datos" de modo que solamente se agreguen a "datos" los registros de "nuevos_datos" cuyo "Valor" sea mayor que 60.

In [8]:
# Crear el DataFrame original
datos = pd.DataFrame({'ID': [1, 2, 3, 4],
                      'Valor': [10, 20, 30, 40]})

# Crear un DataFrame con nuevos datos
nuevos_datos = pd.DataFrame({'ID': [5, 6, 7],
                            'Valor': [50, 60, 70]})

In [9]:
datos

   ID  Valor
0   1     10
1   2     20
2   3     30
3   4     40

In [10]:
nuevos_datos

   ID  Valor
0   5     50
1   6     60
2   7     70

In [11]:
filtro = nuevos_datos['Valor'] <= 60
rta = pd.concat([datos, nuevos_datos.copy().drop(nuevos_datos[filtro].index)], ignore_index=True)
rta

   ID  Valor
0   1     10
1   2     20
2   3     30
3   4     40
4   7     70

In [12]:
filtro_2 = nuevos_datos['Valor'] > 60
pd.concat([datos, nuevos_datos[filtro_2]], ignore_index=True)

   ID  Valor
0   1     10
1   2     20
2   3     30
3   4     40
4   7     70

Dados los dataframes "ventas" y "gastos" combine los dos conjuntos de datos a lo largo de las columnas de modo que sea agregado gastos a ventas.

In [13]:
# Crear DataFrames de ventas y gastos
ventas = pd.DataFrame({'Mes': ['Enero', 'Febrero', 'Marzo'],
                      'Ventas': [10000, 12000, 11000]})

gastos = pd.DataFrame({'Mes': ['Enero', 'Febrero', 'Marzo'],
                       'Gastos': [8000, 9000, 8500]})

In [14]:
ventas

       Mes  Ventas
0    Enero   10000
1  Febrero   12000
2    Marzo   11000

In [15]:
gastos

       Mes  Gastos
0    Enero    8000
1  Febrero    9000
2    Marzo    8500

In [16]:
df_union = ventas.join(gastos.set_index('Mes'), on='Mes')

In [17]:
df_union

       Mes  Ventas  Gastos
0    Enero   10000    8000
1  Febrero   12000    9000
2    Marzo   11000    8500

In [18]:
df_union['Saldo'] = df_union['Ventas'] - df_union['Gastos']
df_union

       Mes  Ventas  Gastos  Saldo
0    Enero   10000    8000   2000
1  Febrero   12000    9000   3000
2    Marzo   11000    8500   2500

In [22]:
df_union = ventas.join(gastos.set_index('Mes'), on='Mes')
df_union['Saldo'] = df_union['Ventas'] - df_union['Gastos']
df_union

       Mes  Ventas  Gastos  Saldo
0    Enero   10000    8000   2000
1  Febrero   12000    9000   3000
2    Marzo   11000    8500   2500