# ***Análisis de Datos y Big data***

## ***Universidad de los Andes***
>## **Dirección de Educación Continua.**
>>## **Formación de habilidades escenciales.**

## **Manipulación de datos en Python v2**
## **Módulo 1**

En el desarrollo de este caso introduciremos las librerías pandas, numpy y matplotlib para el preprocesamiento de un conjunto de datos y el desarrollo de algunas medidas estadísticas descriptivas.


**Hoy aprenderemos a:**
* Cargar bases de datos en Python.
* Mirar con ojo analítico las bases cargadas.
* Ejecutar operaciones de limpieza que involucran filtrar, seleccionar datos, reemplazar y eliminar.
* Manejo de valores vacíos.
</br>**Además, aprenderemos a:**
* Describir la relación entre bases de datos que están en tablas separadas.
* Unir verticalmente cuando queremos agregar datos adicionales.
* Unir hizontalmente cuando queremos agregar columnas a los mismos datos.

## 1. Carga y limpieza de datos

### Carga y primera exploración

En el caso de que la librería no se encuentre instalada ejecutamos el comando

```python
!pip install librería
```

**Importamos las librerías**

In [1]:
import pandas as pd
import numpy as np
import urllib.request

### Introducción a pandas

Poner información sobre pandas e indicar la diferencia entre series y dataframe

![](https://www.cdn.geeksforgeeks.org/wp-content/uploads/creating_dataframe1.png)

**Cargamos los datos**

In [2]:
# Guardamos en ambiente de colab
!wget  https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
# Cargamos en un dataframe de pandas usando el comando pd.read_csv
df_titanic = pd.read_csv('titanic.csv')
# Data set listo para trabajar
df_titanic

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

El [diccionario de la base de datos](https://www.kaggle.com/c/titanic/data) lo encontramos en Kaggle.

El conjunto de datos se encuentra en el `DataFrame` `df`

sobre el objeto creado podemos usar  algunas funciones  para darnos una idea del comportamiento de la información:
```python
df.head(n)  # imprime los primeros n registros del DataFrame
df.tail(n)  # imprime los últimos n registros del DataFrame
df.shape    # imprime el número de columnas y filas del DataFrame
df.columns  # imprime el nombre de las columnas del DataFrame
df.index    # imprime el índice de los registros del DataFrame
df.dtypes   # impreme el tipo de cada una de las columnnas del DataFrame
df.sample(n)# imprime una muestra aleatoria de n registros en el DataFrame
```

In [3]:
display("primeros 3 registros",df_titanic.head(3))
display("últimos registros",df_titanic.tail(3))
display(df_titanic.columns)
display(df_titanic.index)
display("Tipos de registros en el DataFrame",df_titanic.dtypes)
display("Muestra aleatoria de 3 registros",df_titanic.sample(3))
display("dimensión",df_titanic.shape)

'primeros 3 registros'

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

'últimos registros'

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

RangeIndex(start=0, stop=891, step=1)

'Tipos de registros en el DataFrame'

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

'Muestra aleatoria de 3 registros'

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
523,524,1,1,"Hippach, Mrs. Louis Albert (Ida Sophia Fischer)",female,44.0,0,1,111361,57.9792,B18,C
452,453,0,1,"Foreman, Mr. Benjamin Laventall",male,30.0,0,0,113051,27.7500,C111,C
108,109,0,3,"Rekic, Mr. Tido",male,38.0,0,0,349249,7.8958,NaN,S

'dimensión'

(891, 12)

**Presentamos los datos por primera vez**

In [4]:
df_titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

**Ejercicio**: ¿A qué corresponde cada una de las filas? ¿Qué estamos observando en esta tabla? (*unidad de observación*).

**Observamos características que tienen las columnas**

In [5]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

**Describimos los datos cuantitativos a grandes rasgos**

In [6]:
df_titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

**Describimos las variables categóricas**

In [7]:
df_titanic.describe(include='O')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

**Ejercicio:** Pregúntese ¿Qué proporción de las personas en el titanic sobrevivieron? (utilice las exploraciones previas para responderlo)

**Ejercicio 2:** Consulte el diccionario de la base de datos. ¿Qué información registra la columna "Embarked"?

### Manejo de datos duplicados

os dataframes tienen la posibilidad de detectar las filas duplicadas con la función:
```
df.duplicated({columns})
```
Si no especifica {columns}, se busacarán duplicados teniendo en cuenta todas las columnas. Una vez detectados el dtaframe tiene un función para eliminar filas duplicadas, haciendo:

```
df = df.drop_duplicates()
```

In [10]:
df_titanic.duplicated(['Age'])

0      False
1      False
2      False
3      False
4       True
       ...
886     True
887     True
888     True
889     True
890     True
Length: 891, dtype: bool

### Operaciones de filtro y selección

**Seleccionamos columnas individuales por su nombre**

In [25]:
df_titanic['Survived'].mean()

0.3838383838383838

**Ejercicio**: Intente obtener la edad de la persona mayor que viajó en el Titanic (puede utilizar la función max)

In [13]:
# RESPUESTA
df_titanic['Age'].mean()

29.69911764705882

**Podemos hacer operaciones con columnas enteras**

*where* nos sirve para modificar el valor de una columna basado en la información de **otra columna**.

In [14]:
# Crear una columna que nos indique si la persona pagó un tiquete superior a 40 dólares
df_titanic["Muy caro"] = np.where(df_titanic["Fare"]>40,"Caro","Barato")

**Podemos seleccionar a partir de una lista de nombres columnas sobre el *dataframe***

In [15]:
df_titanic[["Fare", "Muy caro"]].head(10)

      Fare Muy caro
0   7.2500   Barato
1  71.2833     Caro
2   7.9250   Barato
3  53.1000     Caro
4   8.0500   Barato
5   8.4583   Barato
6  51.8625     Caro
7  21.0750   Barato
8  11.1333   Barato
9  30.0708   Barato

In [16]:
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Barato
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Caro
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Barato
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Caro
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Barato

**Ejercicio:** Recodificar la columna sexo, creando una nueva columna llamada "Mujer" que tenga el valor de 1 si sexo es "female" y 0 de lo contrario.

In [17]:
# RESPUESTA
df_titanic["Mujer"] = np.where(df_titanic["Sex"]=="female",1,0)

In [18]:
df_titanic[["Mujer","Sex"]]

     Mujer     Sex
0        0    male
1        1  female
2        1  female
3        1  female
4        0    male
..     ...     ...
886      0    male
887      1  female
888      1  female
889      0    male
890      0    male

[891 rows x 2 columns]



### Cálculo de estadísticas resumen

Las medidas estadísticas resumen son de gran ayuda para comprender como es el comportamiento de la distribución de los datos, los objetos `DataFrame` ofrecen facilidades para hacer el cálculo de algunas estadísticas sobre cada una de las variables.

```python
df["var"].value_counts() # Encuentra la frecuencia de las categorias de una columna (la columna debe ser cualitativa)
df["var"].min()          # Encuentra el mínimo de una variable cuantitativa
df["var"].median()       # Encuentra la mediana de una variable cuantitativa
df["var"].mean()         # Encuentra el promedio de una variable cuantitativa
df["var"].max()          # Encuentra el máximo de una variable cuantitativa
df["var"].quantile()     # Encuentra los cuantiles de una variable cuantitativa
```

Con una columna de ceros y unos podemos extraer la proporción de unos calculando la media:

In [19]:
df_titanic["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [21]:
df_titanic["Mujer"].mean()

0.35241301907968575

In [23]:
df_titanic['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [24]:
df_titanic['Age'].quantile([0.2, 0.4, 0.6, 0.8,0.9,0.95, 0.98,0.99,1])

0.20    19.00
0.40    25.00
0.60    31.80
0.80    41.00
0.90    50.00
0.95    56.00
0.98    62.74
0.99    65.87
1.00    80.00
Name: Age, dtype: float64

In [48]:
df_titanic["Mujer"].mean()

0.35241301907968575

**Podemos calcular estadísticos filtrando las filas que cumplen una condición**

In [25]:
df_titanic["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [32]:
condicion = (df_titanic["Embarked"] == "S")&(df_titanic["Mujer"]==1)

In [33]:
# Cuenta de datos para los pasajeros que embarcaron en el puerto de Southampton o que son mujeres
df_titanic[condicion].count()

PassengerId    203
Survived       203
Pclass         203
Name           203
Sex            203
Age            186
SibSp          203
Parch          203
Ticket         203
Fare           203
Cabin           56
Embarked       203
Muy caro       203
Mujer          203
dtype: int64

**Ejercicio:** Tome las filas de personas que no sobrevivieron, muestre el promedio de todas las columnas para ese grupo.

In [34]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Muy caro     891 non-null    object
 13  Mujer        891 non-null    int32
dtypes: float64(2), int32(1), int64(5), object(6)
memory usage: 94.1+ KB

In [37]:
df_titanic_num = df_titanic[['Survived', 'Pclass', 'Age','SibSp','Parch','Fare', 'Mujer']]
df_titanic_num.head()

   Survived  Pclass   Age  SibSp  Parch     Fare  Mujer
0         0       3  22.0      1      0   7.2500      0
1         1       1  38.0      1      0  71.2833      1
2         1       3  26.0      0      0   7.9250      1
3         1       1  35.0      1      0  53.1000      1
4         0       3  35.0      0      0   8.0500      0

In [35]:
df_titanic[df_titanic["Age"] == 80]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro,Mujer
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S,Barato,0

In [41]:
# RESPUESTA
no_sob = (df_titanic["Survived"] == 0)#|(df_titanic["Age"] == 80)
df_titanic_num[no_sob].mean()

Survived     0.000000
Pclass       2.531876
Age         30.626179
SibSp        0.553734
Parch        0.329690
Fare        22.117887
Mujer        0.147541
dtype: float64

In [42]:
# Plus: compararlas con el grupo de los que sí sobrevivieron
df_titanic_num[~no_sob].mean()

Survived     1.000000
Pclass       1.950292
Age         28.343690
SibSp        0.473684
Parch        0.464912
Fare        48.395408
Mujer        0.681287
dtype: float64

### Datos faltantes

Frecuentemente vamos a tener bases de datos con valores faltantes.

Pase lo que pase hay que preguntarnos: ¿por qué los valores están faltantes? --> De ahí vamos a tomar decisiones sobre cómo manejarlos.

**Ejemplo:**
- No tenemos la medición de ritmo cardiaco de todos los miembros del equipo porque algunos no vinieron el día de la medición. ¿Qué hacer con estos valores de ritmo cardiaco?
- No tenemos la medición de puntos en la competencia porque ese día algunos participantes no concursaron. ¿Qué hacer con estos valores de puntos?

Para manipular datos perdidos use la explicación dada el siguiente enlace: [DATOS PERDIDOS](http://ligdigonzalez.com/manipulando-datos-perdidos-en-python/)

**Podemos identificar las filas con datos faltantes en alguna columna**

In [44]:
estaVacio = df_titanic['Age'].isnull()

In [45]:
datosSinEdad = df_titanic[estaVacio]
datosSinEdad.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro,Mujer
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Barato,0
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,Barato,0
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,Barato,1
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,Barato,0
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,Barato,1

**Podemos usar loc para reemplazar los valores vacíos**</br>
(Aunque en este caso lo recomendable sería dejarlos como están).

In [46]:
datosSinEdad.loc[estaVacio, 'Age'] = 0

In [47]:
datosSinEdad.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro,Mujer
5,6,0,3,"Moran, Mr. James",male,0.0,0,0,330877,8.4583,NaN,Q,Barato,0
17,18,1,2,"Williams, Mr. Charles Eugene",male,0.0,0,0,244373,13.0000,NaN,S,Barato,0
19,20,1,3,"Masselmani, Mrs. Fatima",female,0.0,0,0,2649,7.2250,NaN,C,Barato,1
26,27,0,3,"Emir, Mr. Farred Chehab",male,0.0,0,0,2631,7.2250,NaN,C,Barato,0
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,0.0,0,0,330959,7.8792,NaN,Q,Barato,1

**NOTEN:** ¡Modificamos **df_titanic**, pero al revisar **datosSinEdad**, los cambios habían sido aplicados también!

Esto pasa porque cuando almacenamos una "tabla" en una variable, por lo general obtenemos **una referencia a esas observaciones**, no una copia independiente.

Todo lo que hagamos a la tabla original, se podrá ver también al revisar la referencia.

Para obtener una **copia independiente** de una tabla, usamos la función copy()

In [48]:
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro,Mujer
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Barato,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Caro,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Barato,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Caro,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Barato,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Barato,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Barato,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Barato,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Barato,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Barato,0

In [49]:
unaCopiaAparte = df_titanic.copy()

In [50]:
unaCopiaAparte["Ticket"] = 0

In [51]:
unaCopiaAparte.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro,Mujer
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,0,7.2500,NaN,S,Barato,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,0,71.2833,C85,C,Caro,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,0,7.9250,NaN,S,Barato,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,0,53.1000,C123,S,Caro,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,0,8.0500,NaN,S,Barato,0

**Vemos que los cambios se aplican a la copia, pero no a la tabla original**

In [52]:
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro,Mujer
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Barato,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Caro,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Barato,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Caro,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Barato,0

In [ ]:
unaCopiaAparte.head()

**En otras ocasiones, queremos descartar todas las filas que tienen algún dato faltante**

In [53]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Muy caro     891 non-null    object
 13  Mujer        891 non-null    int32
dtypes: float64(2), int32(1), int64(5), object(6)
memory usage: 94.1+ KB

In [54]:
filtro = df_titanic['Cabin'].isnull()

In [55]:
df_titanic_con_cabina = df_titanic.drop(df_titanic[filtro].index)

In [56]:
df_titanic_con_cabina.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro,Mujer
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Caro,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Caro,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Caro,0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,Barato,1
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Barato,1

**NOTEN** ¡Los índices (la cuenta de filas a la izquierda) quedaron locos!

In [57]:
df_titanic_con_cabina.reset_index()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Muy caro,Mujer
0,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Caro,1
1,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Caro,1
2,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Caro,0
3,10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,Barato,1
4,11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Barato,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Caro,1
200,872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,Barato,0
201,879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Caro,1
202,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Barato,1
203,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Barato,0

## 2. Relación y unión de bases de datos

Frecuentemente vamos a tener información en tablas separadas que vamos a tener que unir para poder:
* Relacionar columnas que están en tablas distintas
* Considerar todas filas a la vez, que quedaron en tablas distintas

Existen al menos 4 librerías en Python para hacer estas uniones. Pero nosotros vamos a usar:
- append para pegar filas
- join para pegar columnas

### Uniones (Joins)
Usando la librería pandas se pueden realizar 4 tipos de uniones para cruzar información entre dos fuentes de datos, ver Figura abajo.
* INNER JOIN: este tipo de cruce incluye solo los resgistros que coincieden en las dos tablas
* LEFT JOIN:  en este tipo de cruce se incluyen todos los registros de la primera tabla aunque no aparezcan coincidencias en la segunda. Cuando no hay coincidencias en la segunda tabla los campos correspondientes a esta aparecerán como nulos.
* RIGHT JOIN: en este tipo de cruce se incluyen todos los registros de la segunda tabla aunque no aparezcan coincidencias en la primera. Cuando no hay coincidencias en la primer tabla los campos correspondientes a esta aparecerán como nulos.
* OUTER JOIN O FULL JOIN: combina todos los registros de ambas tablas aunque no existan coincidencias en la otra tabla.

![Los tipos de uniones que se pueden ejecutar en pandas](https://letsdobigdata.files.wordpress.com/2016/03/joins.png)

La combinación a usar depende del análisis que se requiera con los datos. Lo más común es realizar un cruce de tipo Inner Join, debido a que muestra los registros cuando aparecen relacionados en ambas tablas. Sin embargo, en
ocasiones se quiere saber que pasa con todos los registros de la primera tabla aunque no se tengan coincidencias. Alternativamente, quizá, lo menos usual es hacer combinaciones de tipo RIGHT o OUTER. Generalmente, estas son usadas cuando se quiere saber por qué no se tienen coincidencias, o cuáles registros no cumplen con la relación especificada.

### Append: pegarle más filas

DataFrame.**append**(other, ignore_index=False, verify_integrity=False, sort=False)

Parámetros:
<ul>
    <li><b>other</b>: Información para unir. Permite DF, Series, Diccionarios o listas.</li>
    <li><b>ignore_index</b>: Booleano. Si es verdadero el índice queda numerado de 0 a n.</li>
    <li><b>verify_integrity</b>: Booleano. Si es verdadero crea un error al crear un índice duplicado.</li>
    <li><b>sort</b>: Booleano. Deja organizar el DF.</li>
</ul>

El método **append** será deprecado de la librería por lo tanto se recomienda utilizar **concat** en su lugar.

**Ejercicio:** Cuales son los parámetros de la función concat?

In [69]:
# Creamos unas tablas de prueba
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'), index=['x', 'y'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'), index=['x', 'y'])
l1 = ["a", "b"]

In [61]:
l1

['a', 'b']

In [71]:
# Intentemos cambiando el valor en ignore_index y veamos que pasa
df1 = pd.concat([df, df2], ignore_index=False)
df1

   A  B
x  1  2
y  3  4
x  5  6
y  7  8

In [73]:
df = pd.concat([df1, l1], ignore_index=True) # Que pasa si tenemos una lista

TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid

In [76]:
#Podemos convertir la lista en un dataframe y usar concat
l1_df = pd.DataFrame([l1], columns=df.columns)
l1_df
df3 = pd.concat([df1, l1_df], ignore_index=True)
df3

   A  B
0  1  2
1  3  4
2  5  6
3  7  8
4  a  b

**Podemos sólo agregarla en la última posición, si la lista corresponde con las columnas**

In [77]:
df3.loc[len(df3)]=l1
df3

   A  B
0  1  2
1  3  4
2  5  6
3  7  8
4  a  b
5  a  b

### Join: pegarle más columnas

DataFrame.**join**(other, on=None, how='left', lsuffix='', rsuffix='', sort=False, validate=None)

Parámetros:
<ul>
    <li><b>other</b>: Objetos para unir. Permite DF o Series.</li>
    <li><b>on</b>: str. Llave por la cual se van a unir las bases.</li>
    <li><b>how</b>: str. Método para unir los objetos.</li>
    <li><b>lsufix</b>: str. Complementos a los nombres de las variables para diferenciar entre los objetos (Izquierda).</li>
    <li><b>rsufix</b>: str. Complementos a los nombres de las variables para diferenciar entre los objetos (Derecha).</li>
    <li><b>sort</b>: Bool. Ordenar por el índice.</li>
    <li><b>validate</b>: str. Verifica si el cruce se realizó 1:1, 1:m o m:1.</li>
</ul>

In [78]:
dfa = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5'],
                   'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']})
dfb = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']})

In [80]:
dfb

  key   B
0  K0  B0
1  K1  B1
2  K2  B2

In [81]:
dfa.join(dfb, lsuffix='_A', rsuffix='_B')

  key_A   A key_B    B
0    K0  A0    K0   B0
1    K1  A1    K1   B1
2    K2  A2    K2   B2
3    K3  A3   NaN  NaN
4    K4  A4   NaN  NaN
5    K5  A5   NaN  NaN

In [82]:
dfa.join(dfb.set_index('key'), on='key')

  key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2   B2
3  K3  A3  NaN
4  K4  A4  NaN
5  K5  A5  NaN

**También hay configuraciones con las que podemos jugar para quedarnos con las filas que están en una tabla y no en la otra; o bien en ambas, etc. Con esas podemos jugar, o podemos meramente eliminar lo que no queremos después de hacer la unión.**

**Ejercicio:** Pegar la columna C del siguiente dataframe, a la base dfb a partir de la columna key.

¿Qué función deberíamos usar? append o join

In [83]:
dfc = pd.DataFrame({'key': ['K0', 'K2'],
                      'C': ['C0', 'C2']})
dfc

  key   C
0  K0  C0
1  K2  C2

In [84]:
# RESPUESTA:
dfb.join(dfc.set_index('key'), on='key')

  key   B    C
0  K0  B0   C0
1  K1  B1  NaN
2  K2  B2   C2