
# ***Análisis de Datos y Big data***

## ***Universidad de los Andes***
>## **Dirección de Educación Continua.**
>>## **Formación de habilidades escenciales.**

# ***Procesamiento de Medium Data en Python***
# Clase 17

Hoy vamos a explorar la librería Polars y su comparación con Pandas.
También trabajaremos con el concepto de "Medium Data" y realizaremos ejercicios prácticos, incluyendo la conexión a una API para obtener datos abiertos en tiempo real.

![](https://w7.pngwing.com/pngs/838/716/png-transparent-we-bare-bears-characters-polar-bear-giant-panda-grizzly-bear-mammal-polar-bear-white-animals-cat-like-mammal.png)

In [3]:
pip install --upgrade numpy pandas

Requirement already satisfied: numpy in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (2.1.3)
Requirement already satisfied: pandas in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (2.1.3)
Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/29/d4/1244ab8edf173a10fd601f7e13b9566c1b525c4f365d6bee918e68381889/pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata
  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\roygo\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\roygo\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.1.3
    Uninstalling pandas-2.1.3:
      Successfully uninstalled pandas-2.1.3
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [WinError 5] Acceso denegado: 'C:\\Users\\roygo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\~andas\\_libs\\interval.cp312-win_amd64.pyd'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import pandas as pd
import polars as pl
import time
import requests  # Nueva librería para trabajar con la API

# Configurar opciones de pandas para mejor visualización
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# "Medium Data" 

Se refiere a conjuntos de datos que no son lo suficientemente grandes como para necesitar herramientas de Big Data, pero que pueden ser demasiado grandes para ser manejados de manera eficiente con herramientas tradicionales como Pandas.

# Pregunta: 
- ¿Qué tamaño de datos manejas comúnmente en tus proyectos?
- ¿En qué casos has experimentado problemas de rendimiento con Pandas?

- **Tamaño y Escala:** Los datos de tamaño medio son más grandes y complejos que los pequeños conjuntos de datos (como una hoja de cálculo con registros de clientes de una pequeña empresa), pero no alcanzan el volumen o la variedad de Big Data (como los generados por redes sociales a nivel global o sensores de IoT a gran escala).

- **Características:** Estos datos pueden incluir diversas fuentes y tipos, pero aún son manejables con herramientas y tecnologías de análisis de datos estándar. Pueden requerir cierto grado de procesamiento y capacidad de almacenamiento, pero no en la misma medida que el Big Data.

- **Escalabilidad:** Un desafío clave es la escalabilidad. A medida que una organización crece, sus datos pueden empezar a acercarse al umbral del Big Data, lo que requiere una reevaluación de las herramientas y estrategias de manejo de datos.

### Pandas

- **Biblioteca de Código Abierto:** Escrita en Python, proporciona estructuras de datos de alto rendimiento y herramientas de análisis.
- **Estructuras de Datos:** Ofrece dos estructuras principales, Series (unidimensional) y DataFrame (bidimensional).
- **Manipulación y Análisis de Datos:** Ideal para limpieza, transformación, agregación y visualización de datos.
- **Lectura y Escritura de Datos:** Soporta varios formatos como CSV, Excel, SQL, entre otros.
- **Uso de NumPy:** Tradicionalmente, ha utilizado NumPy para operaciones de bajo nivel y manipulación de arrays.

## Polars

Puedes ver más en [Cheat seet](https://franzdiebold.github.io/polars-cheat-sheet/Polars_cheat_sheet.pdf).

Polars combina la flexibilidad y facilidad de uso de Python con la velocidad y escalabilidad de Rust. Es rápido gracias a su núcleo escrito en Rust, un lenguaje eficiente en memoria con rendimiento comparable a C o C++. Polars puede utilizar todos los núcleos de CPU en paralelo y admite conjuntos de datos grandes. Su API intuitiva es fácil de usar para quienes conocen bibliotecas como Pandas. Además, utiliza Apache Arrow para ejecutar consultas vectorizadas y almacenamiento de datos columnar para un procesamiento en memoria rápido. Estas características lo hacen una biblioteca atractiva para el procesamiento de datos.

----

Vamos a cargar los datos que se encuentran en:`https://j.mp/iriscsv`

In [13]:
# Cargar un archivo CSV con Pandas
start_time = time.time()
df_pandas = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
end_time = time.time()
print(f"Pandas cargó los datos en {end_time - start_time} segundos.")

# Cargar un archivo CSV con Polars
start_time = time.time()
df_polars = pl.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
end_time = time.time()
print(f"Polars cargó los datos en {end_time - start_time} segundos.")

Pandas cargó los datos en 0.03300189971923828 segundos.
Polars cargó los datos en 0.023038148880004883 segundos.

### Pregunta: 
¿Qué diferencias observas en los tiempos de carga?

### URL de la API de datos abiertos

In [14]:

url = "https://api.datos.gob.mx/v1/condiciones-atmosfericas"

# Hacer una solicitud GET a la API y medir el tiempo de respuesta
start_time = time.time()
response = requests.get(url)
data_json = response.json()
end_time = time.time()
print(f"La API respondió en {end_time - start_time} segundos.")

La API respondió en 0.26584553718566895 segundos.

In [17]:
# Convertir la respuesta en un DataFrame de Pandas
df_api_pandas = pd.DataFrame(data_json['results'])
df_api_pandas.head()

,_id,cityid,validdateutc,winddirectioncardinal,probabilityofprecip,relativehumidity,name,date-insert,longitude,state,lastreporttime,skydescriptionlong,stateabbr,tempc,latitude,iconcode,windspeedkm
0,5952983359954a0adbf7ab09,MXAS0002,20170627T140000Z,SSE,40,90,Aguascalientes,2017-06-27T17:36:43.084Z,-102.296,Aguascalientes,20170627T092449Z,Tormentas dispersas,AGU,17,21.87982,96,6
1,5952983359954a0adbf7ab0a,MXAS0170,20170627T140000Z,S,60,91,Asientos,2017-06-27T17:36:43.088Z,-102.0893,Aguascalientes,20170627T092453Z,Tormentas dispersas,AGU,15,22.23832,96,5
2,5952983359954a0adbf7ab0b,MXAS0171,20170627T140000Z,E,60,84,Calvillo,2017-06-27T17:36:43.088Z,-102.7188,Aguascalientes,20170627T092453Z,Tormentas dispersas,AGU,19,21.84691,96,2
3,5952983359954a0adbf7ab0c,MXAS0172,20170627T140000Z,S,50,83,Cosío,2017-06-27T17:36:43.088Z,-102.3,Aguascalientes,20170627T092453Z,Tormentas dispersas,AGU,17,22.36641,96,3
4,5952983359954a0adbf7ab0d,MXAS0173,20170627T140000Z,SSO,50,84,El Llano,2017-06-27T17:36:43.089Z,-101.9653,Aguascalientes,20170627T092453Z,Tormentas dispersas,AGU,17,21.91887,96,3

In [20]:
df_api_pandas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    100 non-null    object
 1   cityid                 100 non-null    object
 2   validdateutc           100 non-null    object
 3   winddirectioncardinal  100 non-null    object
 4   probabilityofprecip    100 non-null    object
 5   relativehumidity       100 non-null    object
 6   name                   100 non-null    object
 7   date-insert            100 non-null    object
 8   longitude              100 non-null    object
 9   state                  100 non-null    object
 10  lastreporttime         100 non-null    object
 11  skydescriptionlong     100 non-null    object
 12  stateabbr              100 non-null    object
 13  tempc                  100 non-null    object
 14  latitude               100 non-null    object
 15  iconcode               100 non-null    object
 16  windspeedkm            100 non-null    object
dtypes: object(17)
memory usage: 13.4+ KB

In [31]:
df_api_pandas['probabilityofprecip']

0     40
1     60
2     60
3     50
4     50
5     60
6     60
7     60
8     60
9     70
10    60
11     0
12     0
13     0
14     0
15     0
16    10
17     0
18     0
19    10
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41    10
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96    20
97    20
98    20
99    20
Name: probabilityofprecip, dtype: object

In [19]:
# Convertir la respuesta en un DataFrame de Polars
df_api_polars = pl.DataFrame(data_json['results'])
df_api_polars.head()

shape: (5, 17)
┌─────────────┬──────────┬─────────────┬────────────┬───┬───────┬──────────┬──────────┬────────────┐
│ _id         ┆ cityid   ┆ validdateut ┆ winddirect ┆ … ┆ tempc ┆ latitude ┆ iconcode ┆ windspeedk │
│ ---         ┆ ---      ┆ c           ┆ ioncardina ┆   ┆ ---   ┆ ---      ┆ ---      ┆ m          │
│ str         ┆ str      ┆ ---         ┆ l          ┆   ┆ str   ┆ str      ┆ str      ┆ ---        │
│             ┆          ┆ str         ┆ ---        ┆   ┆       ┆          ┆          ┆ str        │
│             ┆          ┆             ┆ str        ┆   ┆       ┆          ┆          ┆            │
╞═════════════╪══════════╪═════════════╪════════════╪═══╪═══════╪══════════╪══════════╪════════════╡
│ 59529833599 ┆ MXAS0002 ┆ 20170627T14 ┆ SSE        ┆ … ┆ 17    ┆ 21.87982 ┆ 96       ┆ 6          │
│ 54a0adbf7ab ┆          ┆ 0000Z       ┆            ┆   ┆       ┆          ┆          ┆            │
│ 09          ┆          ┆             ┆            ┆   ┆       ┆          ┆          ┆            │
│ 59529833599 ┆ MXAS0170 ┆ 20170627T14 ┆ S          ┆ … ┆ 15    ┆ 22.23832 ┆ 96       ┆ 5          │
│ 54a0adbf7ab ┆          ┆ 0000Z       ┆            ┆   ┆       ┆          ┆          ┆            │
│ 0a          ┆          ┆             ┆            ┆   ┆       ┆          ┆          ┆            │
│ 59529833599 ┆ MXAS0171 ┆ 20170627T14 ┆ E          ┆ … ┆ 19    ┆ 21.84691 ┆ 96       ┆ 2          │
│ 54a0adbf7ab ┆          ┆ 0000Z       ┆            ┆   ┆       ┆          ┆          ┆            │
│ 0b          ┆          ┆             ┆            ┆   ┆       ┆          ┆          ┆            │
│ 59529833599 ┆ MXAS0172 ┆ 20170627T14 ┆ S          ┆ … ┆ 17    ┆ 22.36641 ┆ 96       ┆ 3          │
│ 54a0adbf7ab ┆          ┆ 0000Z       ┆            ┆   ┆       ┆          ┆          ┆            │
│ 0c          ┆          ┆             ┆            ┆   ┆       ┆          ┆          ┆            │
│ 59529833599 ┆ MXAS0173 ┆ 20170627T14 ┆ SSO        ┆ … ┆ 17    ┆ 21.91887 ┆ 96       ┆ 3          │
│ 54a0adbf7ab ┆          ┆ 0000Z       ┆            ┆   ┆       ┆          ┆          ┆            │
│ 0d          ┆          ┆             ┆            ┆   ┆       ┆          ┆          ┆            │
└─────────────┴──────────┴─────────────┴────────────┴───┴───────┴──────────┴──────────┴────────────┘

### Pregunta: 
¿Qué diferencias encuentras en el manejo de los datos provenientes de una API con Pandas y Polars?

### Operación de Filtrado en Pandas

In [30]:
df_api_pandas['probabilityofprecip']

0     40
1     60
2     60
3     50
4     50
5     60
6     60
7     60
8     60
9     70
10    60
11     0
12     0
13     0
14     0
15     0
16    10
17     0
18     0
19    10
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41    10
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96    20
97    20
98    20
99    20
Name: probabilityofprecip, dtype: object

In [32]:
df_pandas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [36]:
df_pandas['sepal_length'].value_counts()

sepal_length
5.0    10
6.3     9
5.1     9
6.7     8
5.7     8
6.4     7
5.5     7
5.8     7
4.9     6
6.0     6
5.4     6
5.6     6
6.1     6
6.5     5
4.8     5
7.7     4
6.9     4
4.6     4
5.2     4
6.2     4
4.4     3
7.2     3
5.9     3
6.8     3
4.7     2
6.6     2
4.3     1
7.0     1
5.3     1
4.5     1
7.1     1
7.3     1
7.6     1
7.4     1
7.9     1
Name: count, dtype: int64

In [37]:
start_time = time.time()
filtered_pandas = df_pandas[(df_pandas['petal_length'] > 3.1)&(df_pandas['sepal_length'] > 4.2)]
end_time = time.time()
print(f"Filtrado en Pandas tomó {end_time - start_time} segundos.")

Filtrado en Pandas tomó 0.002016305923461914 segundos.

### Operación de Filtrado en Polars

In [41]:
start_time = time.time()
filtered_polars = df_polars.filter((pl.col('petal_length') > 3.1)&(pl.col('sepal_length')>4.2))
end_time = time.time()
print(f"Filtrado en Polars tomó {end_time - start_time} segundos.")

Filtrado en Polars tomó 0.0010077953338623047 segundos.

ALgunas de las funciones que son posibles usar son

| Función | Descripción |
|---------|-------------|
| `sum()` | Calcula la suma de los valores de la columna. |
| `mean()` | Calcula el promedio de los valores de la columna. |
| `min()` | Encuentra el valor mínimo en la columna. |
| `max()` | Encuentra el valor máximo en la columna. |
| `count()` | Cuenta el número de elementos en la columna. |
| `median()` | Calcula la mediana de los valores de la columna. |
| `std()` | Calcula la desviación estándar de los valores de la columna. |
| `var()` | Calcula la varianza de los valores de la columna. |
| `quantile(q)` | Calcula el cuantil (por ejemplo, mediana para `q=0.5`). |
| `first()` | Obtiene el primer valor de la columna en un grupo. |
| `last()` | Obtiene el último valor de la columna en un grupo. |
| `unique()` | Devuelve valores únicos de la columna. |
| `list()` | Agrega los valores de la columna en una lista (útil en agrupaciones). |
| `sort()` | Ordena los valores de la columna. |
| `apply(func)` | Aplica una función personalizada a los valores de la columna. |
| `is_null()` | Devuelve una máscara booleana indicando si los valores son nulos. |
| `is_not_null()` | Devuelve una máscara booleana indicando si los valores no son nulos. |
| `is_finite()` | Comprueba si los valores son finitos. |
| `is_infinite()` | Comprueba si los valores son infinitos. |
| `clip(min_val, max_val)` | Limita los valores a un rango definido. |
| `alias(new_name)` | Renombra la columna (útil en agrupaciones y selecciones). |



| Operador | Descripción                                     |
|----------|-------------------------------------------------|
| `&`      | Operador lógico `AND` (Y lógico). Combina dos o más condiciones y todas deben ser verdaderas. |
| `\|`      | Operador lógico `OR` (O lógico). Combina dos o más condiciones y al menos una debe ser verdadera. |
| `~`      | Operador lógico `NOT` (NO lógico). Niega una condición, invirtiendo su resultado. |

### Pregunta: 
¿Cuál fue la diferencia en el tiempo de ejecución entre Pandas y Polars?

### Agrupar y agregar datos en Pandas

In [42]:
df_pandas.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [52]:
start_time = time.time()
grouped_pandas = df_pandas.groupby('species').agg({'sepal_length': 'mean', 'petal_length': 'std','petal_width':'sum'})
end_time = time.time()
print(f"Group by en Pandas tomó {end_time - start_time} segundos.")

Group by en Pandas tomó 0.003018617630004883 segundos.

In [47]:
grouped_pandas

            sepal_length  petal_length
species
setosa             5.006      0.173511
versicolor         5.936      0.469911
virginica          6.588      0.551895

### Agrupar y agregar datos en Polars

In [51]:

start_time = time.time()
grouped_polars = df_polars.groupby('species').agg(pl.col('sepal_length').mean(),pl.col('petal_length').std(),pl.col('petal_width').sum() )
end_time = time.time()
print(f"Group by en Polars tomó {end_time - start_time} segundos.")

Group by en Polars tomó 0.004995822906494141 segundos.

C:\Users\roygo\AppData\Local\Temp\ipykernel_28104\3476840857.py:2: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.
  grouped_polars = df_polars.groupby('species').agg(pl.col('sepal_length').mean(),pl.col('petal_length').std(),pl.col('petal_width').sum() )

In [50]:
grouped_polars

shape: (3, 3)
┌────────────┬──────────────┬──────────────┐
│ species    ┆ sepal_length ┆ petal_length │
│ ---        ┆ ---          ┆ ---          │
│ str        ┆ f64          ┆ f64          │
╞════════════╪══════════════╪══════════════╡
│ setosa     ┆ 5.006        ┆ 0.173511     │
│ virginica  ┆ 6.588        ┆ 0.551895     │
│ versicolor ┆ 5.936        ┆ 0.469911     │
└────────────┴──────────────┴──────────────┘

### Pregunta: ¿Notaste alguna diferencia en la sintaxis o el tiempo de ejecución?

A lo largo de este taller, hemos comparado las librerías Pandas y Polars en términos de carga, filtrado, agrupación, manejo de datos en tiempo real desde una API, y rendimiento.

### Pregunta final: ¿En qué casos considerarías usar Polars en lugar de Pandas en tus proyectos?

### Comparación


#### Lectura de datos
![](https://miro.medium.com/v2/resize:fit:828/format:webp/1*HWibbnVYohpKbpjMmL15rw.png)

#### Operaciones de agregación
![](https://miro.medium.com/v2/resize:fit:828/format:webp/1*7-xfg0arCNVTv4AG3yzTwg.png)

#### Filtros y selección

![](https://miro.medium.com/v2/resize:fit:828/format:webp/1*XR09526SmAUHrBwr0lfFzg.png)

#### Operación de clasificación
![](https://miro.medium.com/v2/resize:fit:828/format:webp/1*Blya6y4zfInlBPe-u2nOEA.png)

### Puedes ver más información

1. https://github.com/pola-rs/polars
2. https://medium.com/cuenex/pandas-2-0-vs-polars-the-ultimate-battle-a378eb75d6d1
3. https://docs.pola.rs/user-guide/